# Generated by Django 3.2.4 on 2021-06-19 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_list', '0007_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='message_comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_comment',
        ),
    ]
